name: bserrors
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9.6
  - conda-forge::ncurses
  - ipykernel
  - pandas
  - numpy==1.26
  - scipy
  - bioconda::bismark
  - fastqc
  - trim-galore
  - multiqc
  - bcftools
  - parallel
  - samtools
  - daler::sratoolkit
  - pip
  - pip:
    - methlab
